---
title: "City Nature Challenges in Österreich, 25.-28. April 2025"
lang: 'de-AT'
execute:
  warning: false
  error: false
  echo: false
order: 1
format:
    html:
        df-print: paged
date: last-modified
date-format: "YYYY-MM-DDTHH:mm:ssZ"
---

- [https://www.citynaturechallenge.at/](https://www.citynaturechallenge.at/)
- [inaturalist.org/projects/city-nature-challenges-in-oesterreich-2025](https://www.inaturalist.org/projects/city-nature-challenges-in-oesterreich-2025)

{{< include _init.qmd >}}

```{r init}
#| include: false
#| cache: false
inatResultsList <- list()
resultsDfList <- list()
for(i in 1:length(projectIds)){
  tempResult <- loadINat(projectIds[i])
  if(!is.null(tempResult)){
    write_csv(tempResult, paste0("data/inat_", projectIds[i], ".csv"), quote = "all")
    inatResultsList[[i]] <- tempResult
  }
}
for(i in 1:length(locationIds)){
  tempResult <- loadObs(locationIds[i], date_after = "2024-01-01", date_before = "2024-01-01")
  if(!is.null(tempResult)){
    write_csv(tempResult, paste0("data/obs_", locationIds[i], ".csv"), quote = "all")
    resultsDfList[[i]] <- tempResult
  }
}
resultsDf <- bind_rows(inatResultsList, resultsDfList)

if(nrow(resultsDf) == 0){
  resultsDf = NULL
}
```

```{r CompareProjects}
#| label: fig-projects
#| fig-cap: "Anzahl der Beobachtungen in den einzelnen Projekt Regionen"
if(!is.null(resultsDf)){
  resultsDf |>
    group_by(project.name) |>
    summarise(n = n()) |>
    ggplot(
      aes(x = reorder(project.name, n), y = n, fill = project.name)
      ) +
    geom_bar(stat = "identity", show.legend = FALSE) +
    coord_flip() +
    labs(x = "", y = "Anzahl der Beobachtungen")+
    theme(
      panel.grid.major.x = element_line()
    )
} else {
  print('Noch keine Beobachtungen')
}
```

## Indizes zwischen den Regionen

```{r CompareProjects2}
if(!is.null(resultsDf)){
  resultsDf |>
    group_by(project.name) |>
    summarise(
      nObserver = n_distinct(user.name),
      nObservations = n(),
      nTaxa = n_distinct(scientificName),
      nResearchGrade = sum(quality_grade == "research", na.rm = TRUE) + sum(validation_status %in% c("J", "A", "P"), na.rm = TRUE),
      ) |>
    select("Region" = project.name, "BeobachterInnen" = nObserver, "Beobachtungen" = nObservations, "Taxa" = nTaxa, "Research Grade" = nResearchGrade) |>
    datatable(rownames = FALSE)
} else {
  print('Noch keine Beobachtungen')
}
```

## Beobachtungen Regnum (iNaturalist)

```{r plotRegnum}
#| label: fig-Regnum
#| fig-cap: Absolute Anzahl der Beobachtungen pro Reich, aufgeteilt in teilnehmende Regionen
if(!is.null(resultsDf)){
  resultsDf |> 
    filter(project.type == 'inat') |>
    drop_na(kingdom) |> 
    count(kingdom, project.name) |> 
    select(n, "Region" = project.name, kingdom) |>
    ggplot() +
      aes(x = kingdom, y = n, fill = Region) +
      geom_bar(position = 'dodge', stat='identity', show.legend = TRUE) +
      labs(
        y = "Beobachtungen pro Reich [#]",
        x = ""
      ) +
      scale_y_continuous(
        labels = scales::label_number(),
      ) +
      coord_flip(clip="off") +
      theme(
        panel.grid.major.x = element_line()
      )
} else {
  print('Noch keine Beobachtungen')
}
```


{{< include _body.qmd >}}
