---
title: "CNC: Urwaltreliktkäfer"
lang: 'de-AT'
bibliography: references.bib
execute:
  warning: false
  error: false
  echo: false
order: 1
date: last-modified
date-format: "YYYY-MM-DDTHH:mm:ssZ"
---

Liste der Coleoptera Reliktarten beobachtet beim CNC für alle Regionen. Artenliste anhand von @eckelt2018.

{{< include _init.qmd >}}

```{r loadRelictSpecies}
#| include: false
#! cache: false
relictSpecies <- readr::read_csv2("data/primeval_forest_relict_beetle.csv")
```


```{r init}
#| include: false
#! cache: false
iNatResultsList <- list()
bioResultList <- list()
for(i in 1:length(projectIds)){
    tempResult <- loadINat(projectIds[i])
    iNatResultsList[[i]] <- tempResult
}
for(i in 1:length(locationIds)){
    tempResult <- loadObs(locationIds[i])
    bioResultList[[i]] <- tempResult
}
inatResults <- bind_rows(iNatResultsList)
bioResults <- bind_rows(bioResultList)
if(nrow(inatResults) == 0){
  resultsDf = NULL
}
if(nrow(bioResults) == 0){
  bioResults = NULL
}
```

## iNaturalist Projekte

```{r relictTable}
if(!is.null(inatResults)){
  inatResults |> 
    filter((taxonRank == 'species' | taxonRank == 'subspecies')) |>
    left_join(relictSpecies, by = c('scientificName' = 'Species')) |>
    filter(!is.na(Category)) |>
    select(
        "Link" = uri_html,
        "Spezies" = scientificName, 
        "Familie" = Family, 
        "Kategorie" = Category, 
        "Region" = project.name, 
        'Umgangspr. Name' = vernacularName
        ) |>
    datatable(
      rownames = FALSE, 
      escape = FALSE,
      filter = list(
        position = 'bottom',
        clear = FALSE,
        plain = TRUE
     ),
      options = list(
        columnDefs = list(list(type = 'html', targets = c(1)))
      )
    )
} else {
  print('Noch keine Beobachtungen')
}
```

## Observation.org Projekte

```{r relictTableBio}
if(!is.null(bioResults)){
  bioResults |> 
    #filter((species_type_name == 'species' | taxonRank == 'subspecies')) |>
    left_join(relictSpecies, by = c('species_detail_scientific_name' = 'Species')) |>
    filter(!is.na(Category)) |>
    select(
        "Link" = uri_html,
        "Spezies" = species_detail_scientific_name, 
        "Familie" = Family, 
        "Kategorie" = Category, 
        "Region" = project.name, 
        'Umgangspr. Name' = species_detail_name
        ) |>
    datatable(
      rownames = FALSE, 
      escape = FALSE,
      filter = list(
        position = 'bottom',
        clear = FALSE,
        plain = TRUE
     ),
      options = list(
        columnDefs = list(list(type = 'html', targets = c(1)))
      )
    )
} else {
  print('Noch keine Beobachtungen')
}
```


## References

::: {#refs}
:::